### ISSUE TITLE
FeaturePoint6d

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-core#101]
Following discussion with @olivier-stasse, I really believe there is an issue in FeaturePoint6d.
The problem arises when one tries to assign a feed-forward velocity.
I do it with
```
feature.frame('desired')
self.feature.setReference(featureDes.name)
featureDes.velocity.value = [0., 0., 0.1, 0., 0., 0.]
```
This results in a velocity which is OPPOSITE to what one would expect, i.e., in the above example, to the foot going DOWN instead of UP (using `feature.frame('current')` does not change this).

If I look at the code in 
https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/feature/feature-point6d.cpp#L406-L417

I can see there is a minus at

https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/feature/feature-point6d.cpp#L415

This is to compute the output signal `errordot`

https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/feature/feature-point6d.cpp#L427-L430

which is then used by the task to compute the kinematic target

https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/task/task.cpp#L230-L271

I could just change the sign, but I really do not understand these two lines:
https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/feature/feature-point6d.cpp#L415-L416

Why the cross product? Why using `Rreft_` for the linear part and `Rt_` for the angular part?

I made a few tests here:
https://gepgitlab.laas.fr/gbuondon/sot-feature-test
where you can compare the API of each feature (which are really inconsistent BTW) and their behavior with given inputs

**Comment by florent-lamiraux** [comment]
I think it worth discussing this point with @jmirabel since we have some weird behaviors on Pyrene when using feed-forward.

**Comment by jmirabel** [comment]
Hi Gabriele,

thanks for your report. It clarifies some things in my minds. You may have a look at https://github.com/stack-of-tasks/sot-core/pull/42#issuecomment-345727582.

**Comment by gabrielebndn** [comment]
@jmirabel developed a new `FeaturePose` which can be used in place of `FeaturePoint6d`. It is fully released now. Closing this issue. Feel free to reopen if you wish.
