### ISSUE TITLE
Bugs in device integrator

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-core#105]
I believe there is a bug in the integration of the freeflyer performed by the device.
Check these lines:

https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/tools/device.cpp#L590-L595

First, RPY is integrated (L591).
Then, the joints are integrated (L595).
**However**, if `controlIN.size()==state_.size()`, as it normally is in our current setting, L595 reduces to `state_ += controlIN * dt;`, **including the freeflyer**.

**This effectively results in a double increment of the freeflyer, and also in errors on the RPY part**.

I have tested this. Please launch a gazebo simulation. Then execute `rosrun dynamic_graph_bridge run_command`. In the interactive shell, insert

```
from dynamic_graph.entity import PyEntityFactoryClass

DeviceTalos = PyEntityFactoryClass('DeviceTalos')
mydev = DeviceTalos('mydev')

mydev.resize(38)
mydev.setPositionBounds([-10.]*38,[10.]*38)
mydev.setVelocityBounds([-10.]*38,[10.]*38)
mydev.set([0.]*38)

mydev.control.value = [1.] + [0.]*37

mydev.increment(1e-3)

mydev.state.value
```

You will see that the result is `(0.002, ...)`, which is wrong, as it should be `(0.001, ...)`.

This is a very serious bug and it needs urgent fixing. It will affect all of our systems.

As another minor fix, I suggest that https://github.com/stack-of-tasks/sot-core/blob/3998459a0a3cf1fd033d1731f687bb6960da1a1c/src/tools/device.cpp#L559 be removed, so that `CONTROL_INPUT_NO_INTEGRATION` can be used with `state_.size()==controlIN.size()` in debug mode.

**Comment by florent-lamiraux** [comment]
We should get rid of this specific handling of the freeflyer and completely switch to pinocchio.

**Comment by olivier-stasse** [comment]
We already agree that the free flyer should be removed from the device.
Estimation of the free flyer position either by odometry, integration should be done outside the device. @NoeliaRamuzat has finished a prototype. Switching to this seems to be appropriate. Wrt to this specific issue control should not be of the size of the state size.

**Comment by gabrielebndn** [comment]
I strongly advise that a quick fix be provided for this until the new device system is set up. Changing the to new device will take some time, we do not know how much, and this is urgent

**Comment by proyan** [comment]
I agree with Florent that we should get rid of this. (and the rpy altogether!).
But as a quick fix, I think the following should be enough, right?
```
  if (vel_control_.size() == state_.size()) {
    integrateRollPitchYaw(state_, vel_control_, dt);
    state_.tail(state_.size()-6) += vel_control_ * dt
  }
  else{
    // Position integration
    state_.tail(controlIN.size()) += vel_control_ * dt;
}
```

**Comment by olivier-stasse** [comment]
@gabrielebndn could you check that the solver is really providing a signal of size 38?  To have it working it should be of size 32. Anyway i agree with the quick fix but  i do not want to break everything.

**Comment by gabrielebndn** [comment]
It is, I've checked. Besides, it is necessary in order to have the free flyer in state

**Comment by gabrielebndn** [comment]
> I agree with Florent that we should get rid of this. (and the rpy altogether!).
> But as a quick fix, I think the following should be enough, right?
> 
> ```
>   if (vel_control_.size() == state_.size()) {
>     integrateRollPitchYaw(state_, vel_control_, dt);
>     state_.tail(state_.size()-6) += vel_control_ * dt
>   }
>   else{
>     // Position integration
>     state_.tail(controlIN.size()) += vel_control_ * dt;
> }
> ```

I'd say `state_.tail(state_.size()-6) += vel_control_.tail(state_.size()-6) * dt` for the first part ^^

**Comment by gabrielebndn** [comment]
> We should get rid of this specific handling of the freeflyer and completely switch to pinocchio.

@florent-lamiraux I do agree with you, we should just Pinocchio's `integrate` method. However, this is not immediate as long as we are relying on RPY in the SoT. See #88. For the moment, I provided a quick fix to this specific bug in #106.

**Comment by olivier-stasse** [comment]
Commit 6abaa1e is not passing the integration test. The robot falls  backward when using test.py in sot-talos. This need to be investigated.

**Comment by gabrielebndn** [comment]
@olivier-stasse surprising. I will check

**Comment by olivier-stasse** [comment]
I was surprised too. Currently the lost obvious is not working ( device, feature abstract, sot, feature generic)

**Comment by gabrielebndn** [comment]
That is very weird, because everything seems right on my side when I use my custom integrator. It seems it even fixed the the estimator!

**Comment by olivier-stasse** [comment]
Fantastic, just to check could you check with the release 4.6.0 of sot-core that I just pushed ?

**Comment by gabrielebndn** [comment]
> Fantastic, could you check with the release 4.6.0 of sot-core that I just pushed ?

I need to do more checks. I haven't run test.py in sot-talos yet

**Comment by gabrielebndn** [comment]
@nim65s told me he is planning a full release. I think we can let him work on that

**Comment by gabrielebndn** [comment]
@olivier-stasse, you may try to put everything on the devel branch (except for those which do not have a devel branch, in which case master should be chosen).
It seems that currently devel branches depend on each other. This should not be, but that's the situation right now

**Comment by olivier-stasse** [comment]
Hi @gabrielebndn some release are not in master for two reasons:
 * Because for some repositories I probably forgot to push the release in master
 * Some of them because the corresponding releases were not validated through the integration test

To have a proper neat directory with the releases I am currently 
testing on my version of robotpkg, you can also try this:
```
cd $HOME
mkdir -p ~/devel-src/dev_env
cd ~devel-src/dev_env
git clone https://github.com/olivier-stasse/robotpkg_helpers.git
sudo apt-get install python3-lark-parser
cd ./robotpkg_helpers/tools
./rpkgh_build_arch_rc.py ../examples/arch_test_rc_sot_core.json
```
The last command is taking some time.

**Comment by olivier-stasse** [comment]
Hi @gabrielebndn My bad every thing is fine. I just simply forgot again to release on the py-sot-core-v3 package breaking the compatibiltiy between both... Sorry for time wasted on this.
I will push the release and hopefully the binaries would be ready this evening by French time.

**Comment by gabrielebndn** [comment]
Dear @olivier-stasse good you have found the problem. Thanks for this and good work!
