### ISSUE TITLE
RPYToMatrix test

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-core#128]
As pointed out by @MaximilienNaveau, the vector-to-rotation.cpp and its headers are dead code.

`RPYToMatrix` provides the same functionnality, and is correctly working:
```python
from dynamic_graph.sot.core.operator import RPYToMatrix
a = RPYToMatrix("banana_rpy")
a.sin.value = [[0,0,-3.14]]
a.sout.recompute(1)
a.sout.value
# Out[30]: '  -0.999999  0.00159265           0\n-0.00159265   -0.999999          -0\n         -0           0           1\n'
```

Then we should deprecate / remove the vector-to-rotation, and add an unit test for this RPYToMatrix.

**Comment by jmirabel** [comment]
> RPYToMatrix provides the same functionnality, and is correctly working:

and unit tested.

> Then we should deprecate / remove the vector-to-rotation, and add an unit test for this RPYToMatrix.

Please, go ahead.

**Comment by nim65s** [comment]
I checked for an unit-test for RPYToMatrix, and didn't find it. Now that you mention it, I checked again, and here it is… Thanks :)

**Comment by olivier-stasse** [comment]
It seems that this issue can be closed. Please feel free to reopen it if you think I misunderstood.

**Comment by nim65s** [comment]
We still have some deadcode, that need deprecation and removal :)
