### ISSUE TITLE
segfault in computeControlLaw

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-core#132]
Hi, 

I have a segfault here:
https://github.com/stack-of-tasks/sot-core/blob/63e289fcd69b22072e76aee45868030dc9a86135/src/sot/sot.cpp#L533

In gdb, If I put a breakpoint just before, and I `print *Jt`, I get:

```
<Eigen::PlainObjectBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, -1, 0, -1, -1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, -1, -1, 0, -1, -1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = 0x0, 
      m_rows = 0, m_cols = 38}}, <No data fields>
```

So my `*Jt` matrix is empty here (looking jacobiSVD doc and trying to use std::cout on the matrix also shows that it is empty). Aren't we missing a initialisation somewhere ?

**Comment by jmirabel** [comment]
Could you provide a bit more context ? Especially about the tasks in the solver. The fact that Jt has 0 rows means one of the task has dimension 0.

**Comment by nim65s** [comment]
I'm running this: https://github.com/stack-of-tasks/sot-talos/blob/release/1.1.1/tests/test.py ; and the segfault arise here: https://github.com/stack-of-tasks/sot-talos/blob/devel/tests/appli.py#L52

**Comment by jmirabel** [comment]
Thanks for the pointers.

**Comment by nim65s** [comment]
If you don't understand it, don't worry, this might be from my setup ; I'll try to reproduce that in 18.04 tomorrow.

**Comment by jmirabel** [comment]
Yes, it does not make sense to me. I didn't look further.

**Comment by olivier-stasse** [comment]
me neither sorry for this.

**Comment by nim65s** [comment]
After a clean rebuild in 18.04 / python2 / official ROS debian packages and in ArchLinux / python 3 / compiled robotpkg ROS packages, this issue appears only in the second case. Let's close this as irrelevant for now.
