### ISSUE TITLE
Multiple definitions of dg namespace shortcut

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/sot-core#147]
In several header files we found 
```c++
namespace dg=dynamicgraph;
```
and often at two locations in the same header file. This is creating ambiguous shortcuts see
https://gitlab.laas.fr/ostasse/sot-core/-/jobs/83790

It is strange that this did not appear before.

**Comment by jmirabel** [comment]
All the C++ code is in namespace `dynamicgraph` so this namespace should be removed.

**Comment by olivier-stasse** [comment]
Fix by #148
