### ISSUE TITLE
rewrite master & devel history

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-core#153]
Hi,

the current master & devel branches have a lot of commits and reverts that polutes the history. @jmirabel suggest to start again form the v4.10.0 tag. If no one complains, I'll do that later this week.

This imply that those who pulled the history will have to reset it, with eg. (if `origin` is your remote for this main repository):

```bash
git fetch origin
git checkout master
git reset --hard origin/master
git checkout devel
git reset --hard origin/devel
```
If you have local changes on your devel branch, you should probably use a `git rebase -i v4.10.0` instead and mark all commits from c2391205 to 7ddb9724 as `drop`.

If you have any trouble with this, please contact me for support, in this issue or by instant messaging.

**Comment by jmirabel** [comment]
Thank for taking care of this.

**Comment by olivier-stasse** [comment]
Thanks a lot and sorry for the mess.

**Comment by nim65s** [comment]
Done
