### ISSUE TITLE
Pinocchio and Dynamic Graph dependencies

### ISSUE THREAD

**Issue by GianniLunardi** [stack-of-tasks/sot-core#202]
Hi everyone,
I have tried to install sot-core-v3 from robotpkg and I have the problems reported in the following screenshots. The package depends on previous versions of other packages (in particular pinocchio and dynamic-graph-v3). If I try to downgrade these packages, then I'll get other dependency problems. Do you know how I can fix it?    

[py-sot-core-dependencies](https://user-images.githubusercontent.com/60383150/188192429-c26d4334-acdf-46b9-831a-5107495b12df.png)
[sot-core-dependencies](https://user-images.githubusercontent.com/60383150/188192433-abb512a4-f72d-4dc8-989e-4925a221935e.png)

**Comment by nim65s** [comment]
Hi @GianniLunardi,
I'm on it, this should be fixed early next week. Sorry for  the inconvenience.

**Comment by nim65s** [comment]
Hi @GianniLunardi,
I think this is fixed, and I've tested on 18.04 with `robotpkg-py27-sot-core-v3` and on 20.04 with `robotpkg-py38-sot-core-v3`. If this good for you too, can you close this issue ?

**Comment by GianniLunardi** [comment]
Hi @nim65s,
Now Python bindings work, but I have the same issue for `robotpkg-sot-core-v3`. However, I see that the package contains already all the `.h` files of the library, thus I think there will be no issues if I want to use the c++ lib. Thank you for the fix!

**Comment by GianniLunardi** [comment]
Hi @nim65s,
Can you also fix `robotpkg-py36-sot-tools-v3` and the related packages dependencies for Ubuntu 18.04? I think it needs the same fix as last time

**Comment by nim65s** [comment]
Hi @GianniLunardi

Using python 3.6 packages on 18.04 is not compatible with ROS, because ROS doesn't provide binary packages for python 3 on 18.04, so I would encorage you to either upgrade your system to 20.04 or 22.04, or to stick with python 2.7 if you need ROS.

But sot-tools doesn't need ROS, so you are right, this robotpkg-py36-sot-tools-v3 should be available. I'll investigate this.

**Comment by nim65s** [comment]
Ok, I had forgotten to remove robotpkg-sot-tools-v3. This is fixed: `apt update && apt install robotpkg-py36-sot-tools-v3` should be working now. Thanks for the report !
