### ISSUE TITLE
Signal "state" in case of a torque controlled device

### ISSUE THREAD

**Issue by proyan** [stack-of-tasks/sot-core#39]
The "state" signal carries the control values/signal being mapped out via the SotAbstractExternalInterface to the robot and external simulators, but this giant feature remains hidden in the robot Device::getControl.

We should change the name "state" to something more meaningful, which shows the control properties of this signal.

However, since this would likely affect any interaction with the robot or a simulator, all the demos and so on, I am asking for suggestions on how/when to do it.

**Comment by proyan** [comment]
@olivier-stasse @andreadelprete @thomas-moulard

**Comment by olivier-stasse** [comment]
Hi Rohan,
The naming is bad. But actually if you look at
https://github.com/stack-of-tasks/sot-core/blob/4912c6e4c0429d7ec793989f56614a6a2f0c7051/src/tools/device.cpp#L390
You will see that state in fact contains control.
We should do a renaming on sot-core using "state" and on the abstract-control-interface using "joints" when each of them means really control.

**Comment by andreadelprete** [comment]
Since we're at it, I've always found the name "state" very confusing. I tend to think of the state of position+velocity (at least). I think a better name would be encoders, and should not contain the floating-base pose. Otherwise, if the floating-base is included, I would call it simply q.

**Comment by andreadelprete** [comment]
Another thing, if you really wanna update the naming convention, you should take care of doing it everywhere, so that you everything keeps working after your changes. I am not sure how much this changes would extend, maybe Olivier has a clearer idea about that.
