### ISSUE TITLE
Euler angles

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/sot-core#45]
The orientation of the free-floating base of the device is expressed using Euler angles. I assume that the internal computations uses quaternions as they are based on Pinocchio.

Is there a reason to keep them at scripting level ?

**Comment by olivier-stasse** [comment]
All the current Koroibot application are using this convention.
That could be a good time to change it as all of this should be ported on the new torque control architecture. We should see that with Thomas Flayols to check what convention is used.

**Comment by jmirabel** [comment]
Closed in favor of #88
