### ISSUE TITLE
periodic call dependency on python

### ISSUE THREAD

**Issue by nim65s** [stack-of-tasks/sot-core#58]
Hi,

In order to fix #57, we have to remove dependencies to the python interpreter in everything that is not related to python bindings. 

So we have to remove a few things from perioc call, as [commandLine](https://github.com/stack-of-tasks/sot-core/blob/master/src/tools/periodic-call.cpp#L198)

**Comment by florent-lamiraux** [comment]
commandLine is not used anymore. It was used by an adhoc interpreter before we replaced this latter by the python bindings. It should be removed everywhere for clarity.

**Comment by nim65s** [comment]
I can find the string `commandLine` in those packages:

- dynamic-graph
- dynamic-graph-python
- sot-core
- sot-dynamic
- sot-dynamic-pinocchio
- sot-dyninv
- sot-pattern-generator
- sot-torque-control

I will open a PR on each of them to remove that.

But, before that, what about [runCmds](https://github.com/stack-of-tasks/sot-core/blob/master/src/tools/periodic-call.cpp#L137) ? Can we also remove that ?

**Comment by nim65s** [comment]
I can only find the string `runCmds` here in sot-core, so that should be OK to remove it too

**Comment by nim65s** [comment]
(same for addCmds / rmCmds)
