### ISSUE TITLE
MetaTaskPosture is too focused on a specific robot

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-core#72]
MetaTaskPosture contains a class variable `postureRange` corresponding to a mapping between the names of given limbs and the corresponding joints (I guess corresponding to HRP2).
In order to specify the desired joints, method `gotoq` takes key-value parameters, where the key corresponds to the name of a limb, and the parameter contains the desired value.
Obviously, this will only work for the specific robot this method was thought for.
(Actually, it is more complicated than this: the desired values can be either given in the key-value pairs, or they can be contained in an overall `qdes`, and I think that if no joints are specified then all joints are considered by default).

I think the joints should be given as indexes and the desired values should be given in an overall `qdes`.
Also I think that it the joints should be directly specified in the constructor (defaulting to all joints).

Do you agree? I can change the code myself if you wish.

**Comment by jmirabel** [comment]
The mapping from joint names to indices should use the robot model provided by Pinocchio.

**Comment by gabrielebndn** [comment]
So, if you look at the code, it is not a one-to-one mapping from a name to a single joint. Instead, it is a one-to-many mapping, from a name to a range of joints, for instance `"rleg": range(6,12)`. So this cannot be done in Pinocchio.
Also I do not think Pinocchio should have anything to do with this. If we want to keep a mapping, then I think the best is passing a dictionary as an argument and keeping it stored as an instance variable. This dictionary may or may not be based on Pinocchio, but this should be invisible to the task itself.

**Comment by olivier-stasse** [comment]
The robot_utils object is suppose to help on this matter. It should be documented properly.
Or may be I did not get your point.
