### ISSUE TITLE
Segmentation fault in computeErrorDot of featurePoint6d

### ISSUE THREAD

**Issue by FannyRis** [stack-of-tasks/sot-core#76]
Multiplication of a dg::Matrix and MatrixRotation results in segmentationFault.
dg::Matrix should be replaced by a Eigen::Matrix<double, 3,3>.

**Comment by jmirabel** [comment]
Could you be more explicit on this SEGV ?

`dg::Matrix` cannot be `Eigen::Matrix<double, 3,3>` in general, but rather `Eigen::MatrixXd`.

**Comment by FannyRis** [comment]
Multiplying an Eigen::MatrixXd of size (3, 3) with a Eigen::Matrix<double, 3,3> leads to SEGV. 
I think @olivier-stasse knows why more precisely

**Comment by jmirabel** [comment]
For reference: https://gist.github.com/olivier-stasse/251d0151f1a540d68aaa81451cdf4d20
The bug is fixed in recent version of Eigen.

**Comment by olivier-stasse** [comment]
Fixed by commit ec3d01
