### ISSUE TITLE
Operator#Selec_of_vector broken?

### ISSUE THREAD

**Issue by jviereck** [stack-of-tasks/sot-core#84]
hi folks,

I am trying to understand "Selec_of_vector" [1]. It looks like there is a bug that "addSelec" command should use the addBound method, but is using the setBound method.

```c++
	boost::function< void( const int&, const int& ) > addBound
	  = boost::bind( &VectorSelecter::setBounds,this,_1,_2 );
	doc = docCommandVoid2("Add a segment to be selected [m,M[.","int (min)","int (max)");
	ADD_COMMAND( "addSelec", makeCommandVoid2(ent,setBound,doc) );
```

Going to take a closer look tomorrow.

[1]: https://github.com/stack-of-tasks/sot-core/blob/master/src/matrix/operator.cpp#L119-L120

**Comment by olivier-stasse** [comment]
Dear @jviereck Thanks a lot, it looks indeed like a problem.
I will check with people in gepetto because it is used in an internal project.
But from the code, it looks like selec could be used instead of addSelec.

**Comment by olivier-stasse** [comment]
Dear @jviereck sorry that it took so long but PR #90 is normally fixing the issue. And I added a unitary test on the repository to validate it is working. Thanks again for reporting this problem.

**Comment by olivier-stasse** [comment]
Fill free to reopen the issue if you feel it is needed.

**Comment by jviereck** [comment]
Thanks for fixing this!

Am 9. Mai 2019 18:14:14 GMT-04:00 schrieb Olivier Stasse <notifications@github.com>:
>Fill free to reopen the issue if you feel it is needed.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/stack-of-tasks/sot-core/issues/84#issuecomment-491087299

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
