### ISSUE TITLE
CONTROL_NO_INTEGRATION

### ISSUE THREAD

**Issue by olivier-stasse** [stack-of-tasks/sot-core#89]
When the device is in CONTROL_NO_INTEGRATION, a control is done on position whereas there is no integration. This is inconsistent.

**Comment by jmirabel** [comment]
What is the meaning of CONTROL_NO_INTEGRATION ?
I have always understood it as: the control signal of device represents a position.

If this is correct, then there shouldn't be an integration and I don't understand the inconsistency. If it isn't correct, I don't understand what you mean.

**Comment by olivier-stasse** [comment]
Sorry, CONTROL_NO_INTEGRATION means that the device class should not perform any integration. In practice two types of control are used: a velocity based control (sot-core),  an acceleration based control (sot-dyninv, sot-torque-control) or a current control (sot-torque-control). In velocity and acceleration based control the integration makes sense. In current control an actuator model would be necessary, and is yet not available.

**Comment by jmirabel** [comment]
Thanks for the clarification.
