### ISSUE TITLE
Computation of constraint projector

### ISSUE THREAD

**Issue by jmirabel** [stack-of-tasks/sot-core#93]
I have always trouble to understand the code in this function:

https://github.com/stack-of-tasks/sot-core/blob/803b02d1707d3343414d081545de9da55a3112d4/src/sot/sot.cpp#L719

I remember having spent time to understand it but I forgot what I understood. I would like to avoid this in the future. A few questions about Constraint class in SoT:
- what was its purpose ?
- is it documented somewhere ?
- is it used somewhere ?

Should we:
- remove it,
- document it,
- replace it by something easier to understand ?

**Comment by jmirabel** [comment]
From discussion with people in the team, the constraint can be remove all together.

**Comment by olivier-stasse** [comment]
Fixed thanks @jmirabel
