### ISSUE TITLE
Dynamically adding and removing tasks

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-core#95]
Hi,
I've been trying to modify the stack of tasks while the controller is active.
When I do
```
robot.sot.remove(task.name)
```
it seems to work perfectly.
However, when I try to push the task
```
robot.sot.push(task.name)
```
I obtain a segfault.

Am I doing anything wrong? Otherwise, this is a problem and it should be fixed.

Is there another way of dynamically modifying the stack?
I think that the ideal is having a signal allowing to deactivate and reactivate tasks, rather than removing them and adding them back.
I found that a convenient way to do it seems to be this:
```
task.controlSelec.value="0"*sot.getSize()
task.controlSelec.value="1"*sot.getSize()
```
Can you confirm? Is there a better way?

**Comment by jmirabel** [comment]
> Am I doing anything wrong? Otherwise, this is a problem and it should be fixed.

As far as I know, no, you aren't doing anything wrong.

> Can you confirm? Is there a better way?

This works, with the drawback of having to compute the decomposition of a null matrix (SVD + a base of the null space). I don't know how costly it is. However, I know it is not costly to avoid this unnecessary operations.
In dynamicgraph::sot::Sot::computeControlLaw, you can modify the loop starting at https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L494 containing https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L560
by handling this case https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L394
earlier. A `continue` when `(bool)(task->controlSelectionSIN( iterTime ))` is false should suffice.

**Comment by gabrielebndn** [comment]
> In dynamicgraph::sot::Sot::computeControlLaw, you can modify the loop starting at
> 
> https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L494
> 
> containing
> https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L560
> 
> 
> by handling this case
> https://github.com/stack-of-tasks/sot-core/blob/7a4dc0a8894fd514b2e78698cd737c9422ea0acc/src/sot/sot.cpp#L394
> 
> 
> earlier. A `continue` when `(bool)(task->controlSelectionSIN( iterTime ))` is false should suffice.

Thanks @jmirabel. For the moment, I'll stay with the solution I found, but I will keep this modification in mind for the future. I suggest to leave this issue open

**Comment by olivier-stasse** [comment]
Dear Gabriele,
Could you give us a bit of more context on which task it is not working ?
I used the following test:
https://github.com/stack-of-tasks/sot-talos/blob/master/tests/test.py
To start it:
```
roslaunch talos_gazebo talos_gazebo.launch
roslaunch roscontrol_sot_talos sot_talos_controller_gazebo.launch
python ./test.py
```
with 
```
rosrun dynamic_graph_bridge run_command
```
I was able to do the following:
```
>>> sot.display()
'+-----------------\n+   SOT     \n+-----------------\n| taskcontactRF\n| taskcontactLF\n| taskcom\n| taskrh\n+-----------------\n'
>>> sot.remove('taskrh')
>>> sot.display()
'+-----------------\n+   SOT     \n+-----------------\n| taskcontactRF\n| taskcontactLF\n| taskcom\n+-----------------\n'
>>> sot.push('taskrh')
>>> sot.display()
'+-----------------\n+   SOT     \n+-----------------\n| taskcontactRF\n| taskcontactLF\n| taskcom\n| taskrh\n+-----------------\n'
>>> 
```
It would be difficult for us to fix your problem if we cannot reproduce it in a programmatic way.

With respect to the suggestion of Joseph, this would indeed be a way to robustify the current solver. But I would not advocate to do this for planning a whole behavoir where the structure of the control is changing. This is probably outside the scope of this issue.

**Comment by gabrielebndn** [comment]
Dear @olivier-stasse, it was part of a complicated test in sot-talos-balance which I now have modified... At this point, I cannot exclude the error was caused by a connectivity mistake from my side. Thanks for investigating! I will close the issue
