### ISSUE TITLE
Python unit tests

### ISSUE THREAD

**Issue by gabrielebndn** [stack-of-tasks/sot-core#99]
Currently, there is only one unit test in Python (https://github.com/stack-of-tasks/sot-core/blob/master/unitTesting/python/op-point-modifier.py) which is not run by the CI. Nothing is in place in order to properly execute Python unit tests. This should be fixed.

**Comment by olivier-stasse** [comment]
Currently they are not still working properly.
They assume that the python module is installed and this make the release process fail.

**Comment by olivier-stasse** [comment]
https://gitlab.laas.fr/stack-of-tasks/sot-core/-/jobs/81614 shows that this is working now. So I will close this issue.
